### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by badbadcode** [AndriyMulyar/semantic-text-similarity#18]
Hello,

thank your for sharing that  it saved me a lot of time and helped me a lot. I would like to reference it in my paper. Do you have a DOI for your github repository? And maybe a bibtex template?

Thanks!

**Comment by AndriyMulyar** [comment]
Hi, thanks for reaching out. Here you go: https://zenodo.org/record/4284013#.X7lkLXVKiM9
