### ISSUE TITLE
Is BERT actually good for semantic similarity.. check the example

### ISSUE THREAD

**Issue by ghost** [AndriyMulyar/semantic-text-similarity#2]
As per score below , second case is more semantic similar than other one. But in actual it is just the opposite.
```
>>> model.predict([("he is an indian", "he has indian citizenship")])
array([3.2054904], dtype=float32)
>>> model.predict([("he is an indian", "he is  not an indian")])
array([3.590286], dtype=float32)
```

**Comment by AndriyMulyar** [comment]
The model implemented is identical to the model in the BERT paper reporting .89 annotator correlation.

**Comment by ghost** [comment]
Hi,
The implementation may be correct but does it worth if results are wrong. I
belive bert embedding is not made for this purpose.
Why to put a code in public which will not give intended results as the
name suggests or the Readme page promises.
Please correct me if I am wrong on BERT usage for this purpose

**Comment by AndriyMulyar** [comment]
Sandeep,

That is an interesting question. Like any model trained over a dataset,
generalization may be difficult due to dataset specific biases that the
model can pick up. If you are interested in these kind of issues, this
recent [ACL paper](https://arxiv.org/abs/1902.01007) may be a good place to
start.

Best,
Andriy

**Comment by sabirdvd** [comment]
Interesting paper. However, according to its main authors, it is not suited for Semantic Textual Similarity (STS) task, since it does not generate a meaningful vector to compute the cosine distance or semantic similarity.

**Comment by timpal0l** [comment]
@sabirdvd What would be a better approach than using the sentence representation from bert for Semantic Similarity...?
