### ISSUE TITLE
Issue in initialising the clinicalSimilarity class.

### ISSUE THREAD

**Issue by spandeyDRG** [AndriyMulyar/semantic-text-similarity#4]
model = ClinicalBertSimilarity()
TypeError: init_weights() takes 1 positional argument but 2 were given

**Comment by vijaysaimutyala** [comment]
@spandeyDRG Any luck with that ?

**Comment by spandeyDRG** [comment]
No its still giving the same error. It seems in some of the classes the parameters setting is mismatch .

**Comment by AndriyMulyar** [comment]
Hi I apologize for the late reply. This has been fixed. I bumped down the version requirements in the setup.py.
